# Generated by Django 4.2 on 2025-02-18 12:46

import cv_tracking_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_text', models.TextField()),
                ('structured_data', models.JSONField(default=dict)),
                ('file_path', models.FileField(upload_to=cv_tracking_system.models.unique_filename, validators=[cv_tracking_system.models.validate_file_size])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
