# Generated by Django 4.2 on 2025-02-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_tracking_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='file_path',
            field=models.FileField(upload_to=''),
        ),
    ]
